config/routes.rb
Rails.application.routes.draw do

  root 'festivals#index'
  resources :festivals

end

app/models/festival.rb
class Festival < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/festivals_controller.rb
class FestivalsController < ApplicationController

  def index
    @festivals = Festival.all
  end

  def show
    @festival = Festival.find(params[:id])
  end

  def new
    @festival = Festival.new
  end

  def create
    Festival.create(festival_params)
    redirect_to(festivals_path)
  end

  def destroy
    festival = Festival.find(params[:id])
    festival.destroy
    redirect_to(festivals_path)
  end

  def edit
    @festival = Festival.find(params[:id])
  end

  def update
    @festival = Festival.find(params[:id])
    @festival.update(festival_params)
    redirect_to(festivals_path)
  end



  private

  def festival_params
    params.require(:festival).permit(:name, :start_date, :end_date, :location, :ticket_price, :image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/festivals/edit.html.erb
<%= form_for @festival do |f| %>
  
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :location %>
  <%= f.text_field :location %>

  <%= f.label :start_date %>
  <%= f.text_field :start_date %>

  <%= f.label :end_date %>
  <%= f.text_field :end_date %>

  <%= f.label :main_headliner %>
  <%= f.text_field :main_headliner %>

  <%= f.label :ticket_price %>
  <%= f.text_field :ticket_price %>

  <%= f.label :image %>
  <%= f.text_field :image %>

  <%= f.submit 'Edit Festival' %>

<% end %>

app/views/festivals/index.html.erb
<div class="four-blocks">
<div class="festivals-list">
    <% @festivals.each do |festival| %>
      <ul class="festival">
<!--         <%= image_tag(festival.image, class: 'festival-logos') %> -->
        <h3><%= link_to(festival.name, festival_path(festival.id)) %></h3>
        <h4><li><%= link_to('DELETE', festival_path(festival.id), method: :delete) %></li></h4>
        <h4><li><%= link_to('EDIT', edit_festival_path(festival.id)) %></li></h4>
      </ul>
    <% end %>
    </div>
</div>

app/views/festivals/new.html.erb
<%= form_for @festival do |f| %>
  
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :location %>
  <%= f.text_field :location %>

  <%= f.label :start_date %>
  <%= f.text_field :start_date %>

  <%= f.label :end_date %>
  <%= f.text_field :end_date %>

  <%= f.label :main_headliner %>
  <%= f.text_field :main_headliner %>

  <%= f.label :ticket_price %>
  <%= f.text_field :ticket_price %>

  <%= f.label :image %>
  <%= f.text_field :image %>

  <%= f.submit 'Create festival!' %>

<% end %>

app/views/festivals/show.html.erb
<h1>testing show page!</h1>

<div class="festival-info">
  <h3><%= @festival.name %></h3>
  <%= image_tag(@festival.image, width: 200) %>
  <h4><%= @festival.location %></h4>
  <h4><%= @festival.start_date %></h4>
  <h4><%= @festival.end_date %></h4>
  <h4>$<%= @festival.ticket_price %></h4>
  <h4><%= @festival.main_headliner %></h4>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Festivals App</title>
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/3.0.3/normalize.min.css">
  <link href='http://fonts.googleapis.com/css?family=Oswald:400,300,700' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<header>
  <nav>
    <h5><li><%= link_to('FESTIVALS', festivals_path) %></li></h5>
    <h5><li><%= link_to('NEW FESTIVAL', new_festival_path) %></li></h5>
  </nav>
</header>

<%= yield %>

</body>
</html>